site_name: "{{ site_name }}"
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - User Guide:
      - Overview: user-guide/overview.md
      - Workflows: user-guide/workflows.md
  - API:
      - Authentication: api/authentication.md
      - Endpoints:
          - Users: api/endpoints/users.md
          - Products: api/endpoints/products.md
          - Orders: api/endpoints/orders.md
      - Error Codes: api/errors.md
  - Developer:
      - Contributing: developer/contributing.md
      - Architecture: developer/architecture.md
  - FAQ: faq.md
  - Changelog: changelog.md
